---
deploymentservers:
  hosts:
    devops1:
      ansible_host: 51.144.19.156
      ansible_port: 22
      ansible_ssh_user: jenkins
    deployment1:
      ansible_host: 13.81.28.109
      ansible_port: 22
      ansible_ssh_user: azureuser
  vars:
    ansible_python_interpreter: /usr/bin/python3
