---
deploymentservers:
  hosts:
    devops1:
      ansible_host: 20.93.162.152
      ansible_port: 22
      ansible_ssh_user: it21871
    deployment1:
      ansible_host: 13.81.28.109
      ansible_port: 22
      ansible_ssh_user: azureuser
    deploymenttest:
      ansible_host: 13.80.42.181
      ansible_port: 22
      ansible_ssh_user: azureuser
  vars:
    ansible_python_interpreter: /usr/bin/python3
