---
deploymentservers:
  hosts:
    deployment1:
      ansible_host: 40.114.244.4
      ansible_port: 22
      ansible_ssh_user: jenkins
    deployment1:
      ansible_host: 13.81.28.109
      ansible_port: 22
      ansible_ssh_user: azureuser
    #deployment2:
      # as ansible host here will be the static deployment vm's ip address of pauliee
      #ansible_host: 18.159.929.4
      #ansible_port: 22
      #ansible_ssh_user: jenkins
  vars:
    ansible_python_interpreter: /usr/bin/python3
