---
- hosts: deploymentservers
  become: true
  vars:
    mail_container_name: movie-mail-system
    mail_container_image: belpanos/movie-mailing

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull mailing Docker image
      docker_image:
        name: "{{ mail_container_image }}"
        source: pull

    - name: Create mailing container
      docker_container:
        name: "{{ mail_container_name }}"
        image: "{{ mail_container_image }}"
        state: present
        ports:
         - "5000:5000"
        volumes:
         - /mail_data

    - name: Starting mail container
      docker_container:
        name: "{{ mail_container_name }}"
        image: "{{ mail_container_image }}"
        state: started
        env:
            SECRET_KEY: "{{ MAIL_SECRET_KEY }}"
            DATABASE_URL: 'sqlite:///./db.sqlite3'
            EMAIL_USER: "{{ MAIL_USER }}"
            EMAIL_PASSWD: "{{ MAIL_PASSWD }}"
            EMAIL_DB_URL_PORT: "{{ DB_FULL_URL }}"
