---
- hosts: all
  become: true
  vars:
    mysql_container_name: MySQLserver
    mysql_container_image: mysql
    db_container_name: movie-database
    db_container_image: belpanos/movie-db
    mail_container_name: movie-mail-system
    mail_container_image: belpanos/movie-mailing
    project_container_name: movies-management-project
    project_container_image: belpanos/movie-main-system

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull mysql Docker image
      docker_image:
        name: "{{ mysql_container_image }}"
        source: pull

    - name: Create mysql container
      docker_container:
        name: "{{ mysql_container_name }}{{ item }}"
        image: "{{ mysql_container_image }}"
     #   command: "{{ default_container_command }}"
        state: present

    - name: Pull db Docker image
      docker_image:
        name: "{{ db_container_image }}"
        source: pull

    - name: Create db container
      docker_container:
        name: "{{ db_container_name }}{{ item }}"
        image: "{{ db_container_image }}"
     #   command: "{{ default_container_command }}"
        state: present

    - name: Pull mailing Docker image
      docker_image:
        name: "{{ mail_container_image }}"
        source: pull

    - name: Create mailing container
      docker_container:
        name: "{{ mail_container_name }}{{ item }}"
        image: "{{ mail_container_image }}"
     #   command: "{{ default_container_command }}"
        state: present

    - name: Pull Main Docker image
      docker_image:
        name: "{{ project_container_image }}"
        source: pull

    - name: Create main container
      docker_container:
        name: "{{ project_container_name }}{{ item }}"
        image: "{{ project_container_image }}"
     #   command: "{{ default_container_command }}"
        state: present
