---
- name: install mysql
  hosts: all
  become: true
  tasks:

  - name: install mysql-server
    apt:
      name: mysql-server
      state: present
      update_cache: yes

  - name: Ensure Pip is installed.
    package:
      name: python3-pip
      state: present

  - name: Make sure pymysql is present
    become: true
    pip:
      name: pymysql
      state: present

  - name: Create database user with name 'mydb' and password '12345' with all database privileges
    mysql_user:
      name: myuser
      password: 12345
      user: root
      host_all: yes
      priv: '*.*!ALL'
      check_implicit_admin: true
      state: present

  - name: ensure mysql started
    service:
      name: mysql
      state: started
      enabled: yes


